export enum AuthProvider {
  EMAIL = 'email',
  GOOGLE = 'google',
  APPLE = 'apple',
  FACEBOOK = 'facebook',
}

export enum EmailVerificationType {
  SIGNUP = 'signup',
  RECOVERY = 'recovery',
  INVITE = 'invite',
  EMAIL_CHANGE = 'email_change',
  EMAIL = 'email',
}

export enum AuthErrorCode {
  SIGNUP_ERROR = 'SIGNUP_ERROR',
  SIGNIN_ERROR = 'SIGNIN_ERROR',
  SIGNOUT_ERROR = 'SIGNOUT_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  REFRESH_ERROR = 'REFRESH_ERROR',
  RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR',
  UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR',
  MAGIC_LINK_ERROR = 'MAGIC_LINK_ERROR',
  VERIFICATION_ERROR = 'VERIFICATION_ERROR',
  GET_USER_ERROR = 'GET_USER_ERROR',
  INVALID_TOKEN = 'INVALID_TOKEN',
  INVALID_PARAMS = 'INVALID_PARAMS',
}

