export enum ErrorCodes {
  // General
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',

  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_REFRESH_ERROR = 'TOKEN_REFRESH_ERROR',

  // PAX API Errors
  DEPARTURE_SEARCH_ERROR = 'DEPARTURE_SEARCH_ERROR',
  ARRIVAL_SEARCH_ERROR = 'ARRIVAL_SEARCH_ERROR',
  CHECKIN_DATES_ERROR = 'CHECKIN_DATES_ERROR',
  PRICE_SEARCH_ERROR = 'PRICE_SEARCH_ERROR',
  GET_OFFERS_ERROR = 'GET_OFFERS_ERROR',
  PRODUCT_INFO_ERROR = 'PRODUCT_INFO_ERROR',
  OFFER_DETAILS_ERROR = 'OFFER_DETAILS_ERROR',
  FARE_RULES_ERROR = 'FARE_RULES_ERROR',

  // Booking Errors
  BEGIN_TRANSACTION_ERROR = 'BEGIN_TRANSACTION_ERROR',
  ADD_SERVICES_ERROR = 'ADD_SERVICES_ERROR',
  REMOVE_SERVICES_ERROR = 'REMOVE_SERVICES_ERROR',
  SET_RESERVATION_INFO_ERROR = 'SET_RESERVATION_INFO_ERROR',
  COMMIT_TRANSACTION_ERROR = 'COMMIT_TRANSACTION_ERROR',
  RESERVATION_DETAIL_ERROR = 'RESERVATION_DETAIL_ERROR',
  RESERVATION_LIST_ERROR = 'RESERVATION_LIST_ERROR',
  CANCELLATION_PENALTY_ERROR = 'CANCELLATION_PENALTY_ERROR',
  CANCEL_RESERVATION_ERROR = 'CANCEL_RESERVATION_ERROR',

  // Flight Module Errors
  FLIGHT_SEARCH_FAILED = 'FLIGHT_SEARCH_FAILED',
  FLIGHT_NO_SEATS = 'FLIGHT_NO_SEATS',
  OFFER_NOT_AVAILABLE = 'OFFER_NOT_AVAILABLE',
  BOOKING_DUPLICATE = 'BOOKING_DUPLICATE',
  BOOKING_FAILED = 'BOOKING_FAILED',

  // Provider
  PROVIDER_TIMEOUT = 'PROVIDER_TIMEOUT',
  PROVIDER_ERROR = 'PROVIDER_ERROR',

  // Rate Limit
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
}

